version: "3"

services:

  php-fpm:
    image: $FUSIONAA_IMAGE_NAME:$FUSIONAAS_VERSION
    container_name: fusionaas-php-fpm
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - fusion
    depends_on:
      - db
    volumes:
      - code:$FUSIONAAS_PATH

  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    ports:
      - $FUSIONAAS_PORT:$FUSIONAAS_PORT
    networks:
      - fusion
    volumes:
      - ${PWD}/nginx_templates:/etc/nginx/templates
      - code:$FUSIONAAS_PATH:ro
    environment:
      - FUSIONAAS_PATH=$FUSIONAAS_PATH
      - FUSIONAAS_PORT=$FUSIONAAS_PORT
      - FUSIONAAS_HOST=$FUSIONAAS_HOST
      - TZ=$TZ

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql57
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fusion
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - TZ=$TZ

volumes:
  mysql-data:
  code:
networks:
  fusion:
